import {chime} from '../audio/sound';
import {coinImage,gestureImage,diceFrame,reelImage,blankDie,hiddenCardImage,casinoOpponent} from './game-art';
import type {Snapshot,Card,PlayState} from '../activity';
import {decorateButton} from './compact-menu';
import {WHEEL,RED,wheelRotation,raceProgress,slotKey,gestureKey,outcomeTone,coinRotation} from './game-model';
import './live-games.css';
import './game-polish.css';
import {gameRules} from './game-rules';
export const liveGameKinds=new Set(['blackjack','roulette','slots','russian','horses','dice','coin','rps']);
type Host={state:()=>Snapshot;mutate:(body:Record<string,unknown>)=>Promise<string>;close:()=>void;route:(key:string)=>void};
const titles:Record<string,string>={blackjack:'Black Jack',roulette:'Roulette',slots:'Machine à sous',russian:'Roulette russe',horses:'Courses de chevaux',dice:'Lancer de dés',coin:'Pile ou face',rps:'Pierre · feuille · ciseaux'};
const labels:Record<string,string>={red:'Rouge',black:'Noir',even:'Pair',odd:'Impair',low:'1–18',high:'19–36',number:'Numéro',pile:'Pile',face:'Face',rock:'Pierre',paper:'Feuille',scissors:'Ciseaux'};
const svg=(body:string,view='0 0 100 100')=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view}" aria-hidden="true">${body}</svg>`;

function symbol(key:string){return reelImage(slotKey(key));}
function die(value:number){const dots:Record<number,number[][]>={1:[[50,50]],2:[[28,28],[72,72]],3:[[28,28],[50,50],[72,72]],4:[[28,28],[72,28],[28,72],[72,72]],5:[[28,28],[72,28],[50,50],[28,72],[72,72]],6:[[28,25],[72,25],[28,50],[72,50],[28,75],[72,75]]};return svg(blankDie()+ (dots[value]??dots[1]).map(([x,y])=>`<circle cx="${x}" cy="${y}" r="7" fill="#382618"/>`).join(''));}
function cylinder(step:number){return svg('<defs><radialGradient id="barrel-metal"><stop stop-color="#b4bbc1"/><stop offset=".6" stop-color="#455665"/><stop offset="1" stop-color="#14212d"/></radialGradient></defs><circle cx="50" cy="50" r="46" fill="url(#barrel-metal)" stroke="#d6aa50" stroke-width="4"/><circle cx="50" cy="50" r="9" fill="#b58c45"/>'+Array.from({length:6},(_,i)=>{const a=(i*60-90)*Math.PI/180;return `<circle cx="${50+29*Math.cos(a)}" cy="${50+29*Math.sin(a)}" r="10" fill="${i<step?'#78826b':'#101923'}" stroke="#a3936f" stroke-width="2"/>`;}).join(''));}
function wheel(){return svg(WHEEL.map((v,i)=>{const a=(i*360/37-90-180/37)*Math.PI/180,b=((i+1)*360/37-90-180/37)*Math.PI/180,m=(a+b)/2;return `<path d="M110 110L${110+99*Math.cos(a)} ${110+99*Math.sin(a)}A99 99 0 0 1 ${110+99*Math.cos(b)} ${110+99*Math.sin(b)}Z" fill="${v===0?'#1c815a':RED.has(v)?'#a62e32':'#101a26'}" stroke="#d2a552"/><text x="${110+87*Math.cos(m)}" y="${113+87*Math.sin(m)}" font-size="7" fill="#fff3c5" text-anchor="middle">${v}</text>`;}).join('')+'<circle cx="110" cy="110" r="65" fill="#54311b" stroke="#d9b168" stroke-width="3"/><circle cx="110" cy="110" r="45" fill="#2e1a12" stroke="#b28b48"/><path d="M110 73v74M73 110h74" stroke="#d4ab51" stroke-width="8"/><circle cx="110" cy="110" r="12" fill="#e8c16c"/>','0 0 220 220');}
function horse(i:number){const boxes=[[150,185,220,175],[145,277,220,175],[145,374,220,175],[140,479,225,175]], [x,y,w,h]=boxes[i];return svg(`<defs><clipPath id="horse-live-${i}"><polygon points="${x+14},${y+78} ${x+55},${y+62} ${x+87},${y+30} ${x+111},${y+10} ${x+134},${y+22} ${x+135},${y+45} ${x+153},${y+55} ${x+189},${y+34} ${x+203},${y+48} ${x+215},${y+83} ${x+185},${y+91} ${x+174},${y+108} ${x+160},${y+135} ${x+162},${y+171} ${x+143},${y+171} ${x+134},${y+116} ${x+100},${y+112} ${x+68},${y+154} ${x+65},${y+174} ${x+44},${y+174} ${x+41},${y+132} ${x+17},${y+149} ${x+3},${y+133}"/></clipPath></defs><image href="/assets/menus/horses.webp" width="1536" height="1024" clip-path="url(#horse-live-${i})"/>`,`${x} ${y} ${w} ${h}`);}
export function openLiveGame(panel:HTMLElement,kind:string,host:Host){
 let wager=10,choice:string|number=kind==='coin'?'pile':kind==='rps'?'rock':kind==='horses'?0:'red',number=0,busy=false,dead=false,notice='',rotation=0,shownRevision=-1;
 let table:HTMLElement,stage:HTMLElement,actions:HTMLElement,result:HTMLElement,stake:HTMLInputElement;
 const runningAnimations=new Set<Animation>();let frame=0,finishTimeline:(()=>void)|undefined;const receipts:{revision:number;message:string;wager:number;payout:number}[]=[];
 const el=(tag:string,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
 const btn=(label:string,fn:()=>void,disabled=false)=>{const b=document.createElement('button');decorateButton(b,label);b.disabled=disabled||busy;b.onclick=()=>{if(!b.disabled&&!busy){chime();fn();}};return b;};
 const art=(cls:string,html:string)=>{const n=el('div',cls);n.innerHTML=html;return n;};
 const matching=()=>host.state().play.kind===kind?host.state().play:undefined;
 const maxBet=()=>Math.min(host.state().balance.wallet,['dice','coin','rps'].includes(kind)?500:host.state().casino.max_bet);
 const lock=()=>{panel.querySelectorAll<HTMLButtonElement|HTMLInputElement>('button,input').forEach(b=>b.disabled=true);panel.setAttribute('aria-busy','true');};
 async function motion(n:HTMLElement,frames:Keyframe[],ms:number,easing='ease-in-out'){if(dead)return;const a=n.animate(frames,{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?40:ms,easing,fill:'forwards'});runningAnimations.add(a);try{await a.finished;}catch{}finally{runningAnimations.delete(a);}}
 function resultText(p:PlayState|undefined){if(!p)return 'Choisissez votre mise et jouez.';if(p.status==='finished'){const gain=(p.payout??0)-(p.wager??0);return `${kind==='roulette'?p.message?.replace('red','rouge').replace('black','noir').replace('green','vert'):p.message??'Manche terminée.'} · Retour : ${p.payout??0} Gold · ${gain>=0?'+':''}${gain} Gold net`;}return p.message??'À votre tour.';}
 async function timeline(ms:number,step:(t:number)=>void){const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?40:ms,start=performance.now();await new Promise<void>(resolve=>{finishTimeline=resolve;const tick=(now:number)=>{if(dead){resolve();return;}const t=Math.min(1,(now-start)/duration);step(t);if(t<1)frame=requestAnimationFrame(tick);else{finishTimeline=undefined;resolve();}};frame=requestAnimationFrame(tick);});}
 function modal(history=false){if(busy||panel.querySelector('.game-help-overlay'))return;const previous=document.activeElement as HTMLElement,overlay=el('div','game-help-overlay'),card=el('section','game-help');card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');card.setAttribute('aria-label',history?'Manches récentes':'Règles du jeu');card.append(el('h2','',history?'Manches récentes':titles[kind]));
  if(history){if(!receipts.length)card.append(el('p','','Aucune manche terminée affichée.'));for(const receipt of [...receipts].reverse()){const item=el('p','game-receipt',`${receipt.message} — Mise : ${receipt.wager} · Retour : ${receipt.payout} Gold`);item.dataset.outcome=outcomeTone(receipt.payout,receipt.wager);card.append(item);}}
  else for(const line of gameRules[kind]??[])card.append(el('p','',line));
  table.inert=true;const close=()=>{table.inert=false;overlay.remove();const label=previous?.getAttribute('aria-label');render();queueMicrotask(()=>Array.from(panel.querySelectorAll<HTMLElement>('[aria-label]')).find(n=>n.getAttribute('aria-label')===label)?.focus({preventScroll:true}));};card.append(btn('Revenir au jeu',close));overlay.append(card);panel.append(overlay);overlay.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){e.preventDefault();card.querySelector<HTMLButtonElement>('button')?.focus();}};overlay.onclick=e=>{if(e.target===overlay)close();};card.querySelector<HTMLButtonElement>('button')?.focus();
 }
 function render(){
  if(dead)return;const s=host.state(),p=matching();panel.hidden=false;panel.className='illustrated live-game';panel.dataset.kind=kind;document.body.classList.add('illustrated-open');panel.replaceChildren();
  table=el('section','game-table game-'+kind+(['dice','coin','rps'].includes(kind)?' tavern-game-table':''));table.setAttribute('aria-label',titles[kind]);panel.append(table);
  const header=el('header','game-header');const heading=el('h2','game-title');const ornament=decorateButton(document.createElement('button'),titles[kind]);heading.append(...Array.from(ornament.childNodes));heading.classList.add('compact-button');if(kind==='rps')heading.classList.add('long-game-title');header.append(el('span','game-wallet',`Portefeuille : ${s.balance.wallet} Gold`),heading);table.append(header);
  stage=el('div','game-playfield');table.append(stage);result=el('p','game-result',notice||resultText(p));result.setAttribute('role','status');if(p?.status==='finished'&&!notice){const tone=outcomeTone(p.payout??0,p.wager??0);result.dataset.outcome=tone;const banner=el('strong','outcome-heading',tone==='win'?'Victoire !':tone==='tie'?'Mise restituée':'Défaite');result.prepend(banner);if(!receipts.some(r=>r.revision===s.play.revision)){receipts.push({revision:s.play.revision,message:p.message??'',wager:p.wager??0,payout:p.payout??0});if(receipts.length>5)receipts.shift();}}table.append(result);
  const controls=el('div','game-controls'),stakeLabel=el('label','game-stake','Mise (Gold)');stake=document.createElement('input');stake.type='number';stake.min='1';stake.max=String(Math.max(1,maxBet()));stake.step='1';stake.value=String(p?.status==='active'?p.wager:wager);stake.setAttribute('aria-label','Mise '+titles[kind]);stake.disabled=p?.status==='active';stake.oninput=()=>{wager=Number(stake.value);validate();};stakeLabel.append(stake);controls.append(btn('−',()=>{wager=Math.max(1,wager-10);stake.value=String(wager);validate();},p?.status==='active'),stakeLabel,btn('+',()=>{wager=Math.min(maxBet(),wager+10);stake.value=String(wager);validate();},p?.status==='active'));controls.firstElementChild?.setAttribute('aria-label','Diminuer la mise');controls.lastElementChild?.setAttribute('aria-label','Augmenter la mise');
  const presets=el('div','game-presets');[10,50,100].forEach(v=>{const chip=btn(String(v),()=>{wager=v;stake.value=String(v);validate();},v>maxBet()||p?.status==='active');chip.classList.add('game-chip');chip.dataset.chip=String(v);chip.setAttribute('aria-pressed',String(wager===v));presets.append(chip);});controls.append(presets);table.append(controls);
  actions=el('div','game-actions');table.append(actions);
  if(!['dice','coin','rps'].includes(kind)&&!s.alley.access.valid){stage.append(el('p','game-empty','Accès à la salle clandestine requis.'));actions.append(btn('Voir le vigile',()=>host.route('guard')));return;}
  if(s.play.status==='active'&&s.play.kind!==kind){stage.append(el('p','game-empty','Une partie est déjà en cours.'));actions.append(btn('Reprendre la partie',()=>host.route(s.play.kind??'casino')));return;}
  if(kind==='blackjack')drawCards(p);
  else if(kind==='roulette')drawWheel(p);
  else if(kind==='slots')drawSlots(p);
  else if(kind==='horses')drawHorses(p,s);
  else if(kind==='russian'){const opponent=el('div','casino-opponent');opponent.append(casinoOpponent(),el('strong','','La hyène'));stage.append(art('game-cylinder',cylinder(p?.step??0)),opponent,el('p','cylinder-count',`${p?.step??0} / 6 chambres`));}
  else if(kind==='dice'){const a=art('game-die player-die',die(Number(p?.player)||1)),b=art('game-die opponent-die',die(Number(p?.opponent)||1));for(const [name,face] of [['Vous',a],['Adversaire',b]] as const){const card=el('section','tavern-dice-card');card.append(diceFrame(),face,el('p','side-name',name));stage.append(card);}}
  else if(kind==='coin'){const coin=art('game-coin-token',coinArt(p?.opponent==='face'?'Face':'Pile'));stage.append(coin);choices(stage,['pile','face']);}
  else{const choicesBox=el('div','rps-choices');choices(choicesBox,['rock','paper','scissors']);stage.append(choicesBox);const duel=el('div','rps-duel');if(p){for(const [name,key] of [['Vous',String(p.player)],['Adversaire',String(p.opponent)]]){const side=el('div','rps-side');side.append(el('p','',name),gestureImage(key),el('span','',labels[gestureKey(key)]??key));duel.append(side);}}else duel.textContent='Choisissez votre geste.';stage.append(duel);}
  if(p?.status==='active'&&kind==='blackjack')actions.append(btn('Tirer une carte',()=>void play('hit')),btn('Rester',()=>void play('stand')));
  else if(p?.status==='active'&&kind==='russian')actions.append(btn('Tenter',()=>void play('try')));
  else{const b=btn(p?.status==='finished'?'Rejouer':kind==='blackjack'?'Distribuer':kind==='roulette'?'Lancer la roulette':kind==='slots'?'Lancer les rouleaux':kind==='horses'?'Lancer la course':kind==='russian'?'Commencer':'Jouer',()=>void play());b.dataset.start='true';actions.append(b);}
  actions.append(btn('Retour',()=>{if(!busy)host.route(['dice','coin','rps'].includes(kind)?'games':'casino');}));const extras=el('div','game-extras');extras.append(btn('Règles',()=>modal()),btn('Manches récentes',()=>modal(true)));table.append(extras);panel.scrollTop=0;validate();shownRevision=s.play.revision;
 }
 function validate(){panel.querySelectorAll<HTMLButtonElement>('[data-start]').forEach(b=>b.disabled=busy||!Number.isInteger(wager)||wager<1||wager>maxBet()||host.state().play.status==='active');panel.querySelectorAll<HTMLElement>('[data-chip]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.chip)===wager)));stake.setAttribute('aria-invalid',String(!Number.isInteger(wager)||wager<1||wager>maxBet()));}
 function choices(parent:HTMLElement,keys:string[]){const row=el('div','game-choice-row');keys.forEach(k=>{const b=btn(labels[k],()=>{choice=k;render();});b.classList.toggle('selected',choice===k);b.setAttribute('aria-pressed',String(choice===k));if(kind==='rps'){b.classList.add('gesture-choice');b.prepend(gestureImage(k));}row.append(b);});parent.append(row);}
 function coinArt(label:string){return coinImage(label);}
 function drawCards(p:PlayState|undefined){for(const [who,cards,total] of [['Croupier',p?.dealer??[],p?.dealer_total],['Vous',Array.isArray(p?.player)?p.player:[],p?.player_total]] as const){const hand=el('section','game-hand');hand.append(el('h3','',`${who}${total===undefined?'':' · '+total}`));const row=el('div','game-cards');if(!cards.length)row.append(el('div','card-slot','Cartes à distribuer'));cards.forEach((c:Card,i:number)=>{const card=document.createElement('button');card.className='live-card'+(c.hidden?' card-back':['♥','♦'].includes(c.suit??'')?' card-red':'');card.dataset.card=who+'-'+i;card.setAttribute('aria-label',c.hidden?'Carte cachée':`${c.rank} ${c.suit}`);card.innerHTML=c.hidden?hiddenCardImage():`<span class="card-corner">${c.rank}<br>${c.suit}</span><span class="card-suit">${c.suit}</span><span class="card-corner card-bottom">${c.rank}<br>${c.suit}</span>`;card.onclick=()=>{if(!busy&&!c.hidden){card.classList.toggle('card-selected');card.setAttribute('aria-pressed',String(card.classList.contains('card-selected')));}};row.append(card);});hand.append(row);stage.append(hand);}}
 function drawWheel(p:PlayState|undefined){const area=el('div','game-wheel-area'),rotor=art('game-wheel',wheel());if(p?.number!==undefined)rotation=wheelRotation(p.number,rotation)%360;rotor.style.transform=`rotate(${rotation}deg)`;area.append(rotor,el('span','game-wheel-pointer','▼'),el('span','game-ball'));stage.append(area);const bets=el('div','roulette-bets');choices(bets,['red','black','even','odd','low','high']);const numbered=el('div','number-bets');const toggle=btn(choice==='number'?`Numéro ${number}`:'Choisir un numéro',()=>{choice='number';render();});numbered.append(toggle);{const grid=el('div','roulette-numbers');for(let i=0;i<=36;i++){const b=document.createElement('button');b.textContent=String(i);b.className=i===0?'zero':RED.has(i)?'red':'black';b.classList.toggle('selected',choice==='number'&&number===i);if(p?.number===i)b.dataset.resultNumber='true';b.setAttribute('aria-label','Numéro '+i);b.setAttribute('aria-pressed',String(choice==='number'&&number===i));b.onclick=()=>{choice='number';number=i;render();};grid.append(b);}numbered.append(grid);}bets.append(numbered);stage.append(bets);}
 function drawSlots(p:PlayState|undefined){const cabinet=el('div','game-slot-machine'),reels=el('div','live-reels');for(let i=0;i<3;i++){const reel=el('div','live-reel');reel.dataset.reel=String(i);reel.dataset.symbol=slotKey(p?.reels?.[i]??['cherry','bell','diamond'][i]);reel.append(art('reel-symbol',symbol(reel.dataset.symbol)));reels.append(reel);}cabinet.append(el('div','slot-marquee','♦ ALTHÉRYA ♦'),reels);const lever=btn('Actionner le levier',()=>void play());lever.classList.add('slot-lever');lever.dataset.start='true';lever.setAttribute('aria-label','Actionner le levier');cabinet.append(lever);stage.append(cabinet);}
 function drawHorses(p:PlayState|undefined,s:Snapshot){const track=el('div','live-track');for(let i=0;i<4;i++){const lane=el('div','live-lane');lane.append(el('span','lane-label',s.casino.horses[i]));const run=art('live-horse',horse(i));run.dataset.runner=String(i);run.style.left=(p?.winner===undefined?0:raceProgress(1,p.winner)[i])*78+'%';lane.append(run,el('span','finish-line'));track.append(lane);}stage.append(track);const choicesRow=el('div','horse-bets');s.casino.horses.forEach((name,i)=>{const b=btn(`${name} ×${p?.odds?.[i]??s.casino.odds[i]}`,()=>{choice=i;render();});b.classList.toggle('selected',choice===i);b.setAttribute('aria-pressed',String(choice===i));choicesRow.append(b);});stage.append(choicesRow);}
 async function play(key?:string){if(busy||dead)return;const old=matching();busy=true;notice='';lock();result.textContent='Partie en cours…';const oldCards=new Set(Array.from(panel.querySelectorAll<HTMLElement>('[data-card]'),n=>n.dataset.card));try{
  await host.mutate(key?{action:'game_step',key,revision:host.state().play.revision}:{action:'game_start',key:kind,wager,choice,number,revision:host.state().play.revision});if(dead)return;const p=matching();if(!p)throw Error('Résultat indisponible.');
  table.dataset.animating='true';result.removeAttribute('data-outcome');result.textContent=kind==='blackjack'?'Distribution des cartes…':kind==='roulette'?'La roue tourne…':kind==='slots'?'Les rouleaux tournent…':kind==='horses'?'La course est lancée…':'À vous de jouer…';
  if(kind==='blackjack'){
   stage.replaceChildren();drawCards(p);panel.querySelectorAll('.game-hand h3').forEach(n=>n.textContent=n.textContent?.startsWith('Croupier')?'Croupier':'Vous');const cards=Array.from(stage.querySelectorAll<HTMLElement>('[data-card]')).filter(n=>!oldCards.has(n.dataset.card)||(old?.status==='active'&&p.status==='finished'&&n.classList.contains('live-card')));await Promise.all(cards.map((c,i)=>motion(c,[{opacity:0,transform:'translate(120px,-100px) rotate(12deg)'},{opacity:1,transform:'translate(0,0) rotate(0)'}],500+i*120)));
  }else if(kind==='roulette'){
   const rotor=stage.querySelector<HTMLElement>('.game-wheel')!,ball=stage.querySelector<HTMLElement>('.game-ball')!,target=wheelRotation(p.number??0,rotation);await Promise.all([motion(rotor,[{transform:`rotate(${rotation}deg)`},{transform:`rotate(${target}deg)`}],3200,'cubic-bezier(.12,.6,.18,1)'),motion(ball,[{transform:'rotate(0deg)'},{transform:'rotate(-2160deg)'}],3200,'cubic-bezier(.12,.6,.18,1)')]);rotation=target;
  }else if(kind==='slots'){
   await Promise.all(Array.from(stage.querySelectorAll<HTMLElement>('.live-reel')).map(async(reel,i)=>{const strip=el('div','live-reel-strip');const keys=['cherry','bell','diamond','crown','seven'];for(let j=0;j<24;j++)strip.append(art('reel-symbol',symbol(j===23?p.reels?.[i]??'diamond':keys[(j+i)%5])));reel.replaceChildren(strip);await motion(strip,[{transform:'translateY(0)'},{transform:'translateY(-95.833333%)'}],2000+i*450,'cubic-bezier(.12,.6,.18,1)');}));
  }else if(kind==='horses'){
   const runners=Array.from(stage.querySelectorAll<HTMLElement>('[data-runner]'));runners.forEach(n=>n.classList.add('galloping'));await timeline(4500,t=>{const values=raceProgress(t,p.winner??0);runners.forEach((n,i)=>n.style.left=values[i]*78+'%');stage.querySelectorAll<HTMLElement>('.live-lane').forEach(n=>n.style.backgroundPosition=`${-t*700}px 0`);});
  }else if(kind==='russian'){const drum=stage.querySelector<HTMLElement>('.game-cylinder')!;await motion(drum,[{transform:'rotate(0deg)'},{transform:'rotate(1080deg)'}],1400,'cubic-bezier(.15,.7,.2,1)');}
  else if(kind==='dice'){const faces=Array.from(stage.querySelectorAll<HTMLElement>('.game-die'));let last=-1;await Promise.all([timeline(1700,t=>{const beat=Math.floor(t*18);if(beat!==last){last=beat;faces.forEach((n,i)=>n.innerHTML=die(t===1?Number(i?p.opponent:p.player):1+(beat+i*3)%6));}}),...faces.map((n,i)=>motion(n,[{transform:'rotateX(0) rotateZ(0) translateY(0)'},{transform:`rotateX(${i?210:-210}deg) rotateZ(145deg) translateY(-40px)`,offset:.35},{transform:'rotateX(340deg) rotateZ(300deg) translateY(-12px)',offset:.75},{transform:'rotateX(360deg) rotateZ(360deg) translateY(0)'}],1700))]);}
  else if(kind==='coin'){const token=stage.querySelector<HTMLElement>('.game-coin-token')!;token.innerHTML=`<div class="coin-face coin-front">${coinImage('Pile')}</div><div class="coin-face coin-back">${coinImage('Face')}</div>`;await motion(token,[{transform:'translateY(0) rotateY(0deg) rotateZ(0)'},{transform:'translateY(-60px) rotateY(1260deg) rotateZ(-8deg)',offset:.5},{transform:`translateY(0) rotateY(${coinRotation(String(p.opponent))}deg) rotateZ(0)`}],2200,'cubic-bezier(.2,.7,.15,1)');}
  else{const reveal=stage.querySelector<HTMLElement>('.rps-duel')!;let beat=-1;await Promise.all([timeline(1800,t=>{const phase=Math.min(2,Math.floor(t*3));if(phase!==beat){beat=phase;reveal.replaceChildren(gestureImage(['rock','paper','scissors'][phase]),el('strong','', ['Pierre…','Feuille…','Ciseaux !'][phase]));}}),motion(reveal,[{transform:'scale(.85)',opacity:.4},{transform:'scale(1.04)',opacity:1,offset:.7},{transform:'scale(1)',opacity:1}],1800)]);}

 }catch(e){notice=String(e);}finally{busy=false;if(!dead){render();panel.setAttribute('aria-busy','false');const finished=matching();if(!notice&&finished?.status==='finished')chime((finished.payout??0)>(finished.wager??0));}}}
 render();panel.onkeydown=e=>{if(e.key==='Escape'&&!busy)host.close();};
 return{update(){if(panel.querySelector('.game-help-overlay'))return;if(!busy&&host.state().play.revision!==shownRevision)render();else if(!busy){const wallet=panel.querySelector('.game-wallet');if(wallet)wallet.textContent=`Portefeuille : ${host.state().balance.wallet} Gold`;validate();}},destroy(){dead=true;runningAnimations.forEach(a=>a.cancel());cancelAnimationFrame(frame);finishTimeline?.();panel.onkeydown=null;document.body.classList.remove('illustrated-open');}};
}
