import {sizeMenu,watchMenuSize,materialField,fieldText} from './menu-layout';
import type {Snapshot} from '../activity';
import {equipmentArt,resourceArt} from './catalog-art';
import {themedHeader} from './compact-menu';
import {node as el,ornamentButton,menuHeading,assetSlice,trapMenu} from './menu-kit';
import {worldButtonArt} from './world-assets';
import {timeLabel} from './game-model';
import './refined-menus.css';
type Host={state:()=>Snapshot;mutate:(body:Record<string,unknown>)=>Promise<string>;close:()=>void;route:(key:string)=>void};
export const refinedKinds=new Set(['market','forge','drinks','guard','robber','profile','world','story','khaz','ashkar']);
export function openRefined(panel:HTMLElement,kind:string,host:Host){
 let planning=false,busy=false,dead=false,message='',selected=kind==='forge'?'axe':'beer',profileTab='Résumé',inventoryPage=0,chapter=host.state().chapters.find(c=>c.unlocked)?.chapter??1,guess='';const texts=new Map<number,string>();
 const titles:Record<string,string>={market:'Marché de Legacy',forge:'Forge de IV',drinks:'Le tavernier',guard:'Le vigile',robber:'Planifier un braquage',profile:'Mon personnage',world:'Le monde d’Elyndor',khaz:'Forge de Khaz’goram',ashkar:'Tour d’Ashkar',story:'Le livre du troubadour'};
 const btn=(label:string,fn:()=>void,disabled=false)=>ornamentButton(label,fn,disabled||busy);
 const back=()=>host.route(['khaz','ashkar'].includes(kind)?'world':kind==='forge'||kind==='market'?'hub':kind==='guard'||kind==='robber'?'alley':kind==='world'||kind==='profile'?'hub':'tavern');
 async function run(body:Record<string,unknown>,after?:(text:string)=>void){if(busy||dead)return;busy=true;message='';draw();try{const t=await host.mutate(body);if(dead)return;after?after(t):message=t;}catch(e){if(!dead)message=String(e);}finally{busy=false;if(!dead)draw();}}
 function stat(parent:HTMLElement,label:string,value:string){const c=el('div','menu-stat');c.append(el('span','',label),el('strong','',value));parent.append(c);}
 function gearName(s:Snapshot,key:string,tier:number){return key==='bag'?s.bags[String(tier)]?.name:s.tools[String(tier)]?.[key];}
 function portrait(file:string,box:[number,number,number,number]){const p=el('figure','npc-portrait');p.append(assetSlice('/assets/menus/'+file+'.webp',...box));return p;}
 function draw(){if(dead)return;if(['market','forge','drinks','guard','robber'].includes(kind)){drawOriginal();return;}const scroll=panel.scrollTop,bookScroll=panel.querySelector<HTMLElement>('.book-prose')?.scrollTop??0,oldChapter=panel.querySelector('.book-page')?.getAttribute('aria-label'),mapViewport=panel.querySelector<HTMLElement>('.map-viewport'),mapScroll=[mapViewport?.scrollLeft??0,mapViewport?.scrollTop??0];const focused=panel.contains(document.activeElement)?document.activeElement?.getAttribute('aria-label'):null,s=host.state();panel.hidden=false;panel.className='refined-menu refined-'+kind;panel.dataset.kind=kind;panel.setAttribute('aria-label',titles[kind]);panel.setAttribute('aria-busy',String(busy));panel.replaceChildren();document.body.classList.add('illustrated-open');const header=el('div','menu-header');if(kind==='forge'){header.append(themedHeader('forge-design'));const h=el('h2','sr-only',titles[kind]);header.append(h);}else header.append(menuHeading(titles[kind]));panel.append(header);const body=el('section','menu-content');panel.append(body);
 if(kind==='market')marketHome(body,s);else if(kind==='forge')forge(body,s);else if(kind==='drinks')drinks(body,s);else if(kind==='guard'||kind==='robber')alley(body,s);else if(kind==='profile')profile(body,s);else if(kind==='world')world(body,s);else if(kind==='khaz'||kind==='ashkar')worldEntrance(body,s);else story(body,s);
 if(message){const n=el('p','menu-notice',message);n.setAttribute('role','status');body.append(n);}if(busy){const n=el('p','menu-loading','Chargement…');n.setAttribute('role','status');body.append(n);}const footer=el('div','menu-footer');footer.append(btn(['khaz','ashkar'].includes(kind)?'Retour au monde':kind==='market'?'Partir':kind==='guard'||kind==='robber'?'Retour à la ruelle':kind==='drinks'||kind==='story'?'Retour à la taverne':'Retour en ville',back));if(kind!=='world')panel.append(footer);panel.scrollTop=scroll;const prose=panel.querySelector<HTMLElement>('.book-prose');if(prose&&oldChapter==='Chapitre '+chapter)prose.scrollTop=bookScroll;const map=panel.querySelector<HTMLElement>('.map-viewport');if(map){map.scrollLeft=mapScroll[0];map.scrollTop=mapScroll[1];}if(focused)Array.from(panel.querySelectorAll<HTMLElement>('[aria-label]')).find(n=>n.getAttribute('aria-label')===focused)?.focus({preventScroll:true});}
 function drawOriginal(){
  const s=host.state();panel.hidden=false;panel.className='illustrated restored-art restored-'+kind;panel.dataset.kind=kind;panel.setAttribute('aria-label',titles[kind]);panel.setAttribute('aria-busy',String(busy));panel.replaceChildren();document.body.classList.add('illustrated-open');
  sizeMenu(panel,kind==='market'?2.5:1.5,['guard','robber'].includes(kind)?760:1180);const stage=el('div','art-stage');panel.append(stage);const image=new Image();image.className='art-image';image.alt=titles[kind];image.src=kind==='market'?'/assets/catalog/merchant-design.webp':'/assets/menus/'+kind+'.webp';image.onload=()=>{if(image.isConnected)sizeMenu(panel,image.naturalWidth/image.naturalHeight,['guard','robber'].includes(kind)?760:1180);};stage.append(image);
  const place=(n:HTMLElement,x:number,y:number,w:number,h:number)=>{Object.assign(n.style,{left:x+'%',top:y+'%',width:w+'%',height:h+'%'});stage.append(n);return n;};
  const value=(text:string,x:number,y:number,w:number,h:number,cls='')=>place(materialField(el('div','art-overlay art-mask '+cls,text),kind,cls.includes('art-paper')?'paper':kind==='forge'||kind==='robber'?'wood':'blue'),x,y,w,h);
  const hit=(label:string,x:number,y:number,w:number,h:number,fn:()=>void,disabled=false)=>{const b=document.createElement('button');b.type='button';b.className='art-hit';b.setAttribute('aria-label',label);b.title=label;b.disabled=disabled||busy;b.onclick=()=>{if(!b.disabled)fn();};place(b,x,y,w,h);return b;};
  if(kind==='forge'){
   const keys=['axe','pickaxe','spear','bag'].filter(k=>s.catalog[k]);if(!keys.includes(selected))selected=keys[0];
   keys.forEach((key,i)=>{const b=hit(({axe:'Hache',pickaxe:'Pioche',spear:'Lance',bag:'Sac'} as Record<string,string>)[key],9+i*21,25,20,11,()=>{selected=key;message='';draw();});b.classList.toggle('selected',selected===key);});
   const current=s.gear[selected+'_level'],next=current+1,max=next>5,owned=s.owned[selected];
   [current,Math.min(5,next)].forEach((tier,i)=>{const art=value('',7+i*58,51,11,16);art.append(equipmentArt(selected,tier));value(i===0&&!owned?'Non possédé':gearName(s,selected,tier)??s.catalog[selected].name,20+i*58,54,17,6);value(max&&i===1?'Palier maximum':`Palier ${tier}`,24+i*58,60,10,5,'art-small');});
   const recipe=(selected==='bag'?s.bag_recipes:s.recipes)[next]??{},cost=s.forge_gold[selected==='bag'?'bag':'tool'][next]??0,level=s.forge_levels[next]??0;
   const materials=value('',20,77,48,7,'art-small');Object.entries(recipe).forEach(([name,qty])=>materials.append(el('span','',`${name} : ${s.resources[name]??0} / ${qty}`)));if(max)materials.textContent='Palier maximum atteint';
   value(`Niveau requis : ${level}`,80,73,12,4,'art-small art-wood');value(`Coût : ${cost} Gold`,80,81,12,4,'art-small art-wood');
   hit('Améliorer',16,87,40,11,()=>void run({action:'upgrade',key:selected}),!owned||(max||s.level<level||s.balance.wallet<cost||Object.entries(recipe).some(([n,q])=>(s.resources[n]??0)<q)));
   hit('Retour en ville',60,88,24,10,back);
  }else if(kind==='drinks'){
   s.tavern.drinks_catalog.forEach((d,i)=>{const b=hit(d.name,7+(i%3)*29,15+Math.floor(i/3)*34,28,33,()=>{selected=d.key;message='';draw();},!d.available);b.classList.toggle('selected',d.key===selected);});
   hit('Commander',31,83,39,10,()=>void run({action:'drink',key:selected}),!s.tavern.drinks_catalog.find(d=>d.key===selected)?.available||s.tavern.remaining_today===0||s.tavern.cooldown_seconds>0);hit('Retour à la taverne',39,93,25,6,back);
   if(s.tavern.cooldown_seconds>0){const timer=value('',31,78,39,5,'art-small drink-timer');timer.dataset.deadline=String(Date.now()+s.tavern.cooldown_seconds*1000);tick();}
  }else if(kind==='guard'){
   if(s.alley.access.valid||s.alley.vip)value(s.alley.access.valid?'Accès accordé':'Entrée VIP',61,44.7,25,5.4,'art-paper guard-status');if(s.alley.access.valid||s.alley.vip||s.alley.fee!==150)value(s.alley.access.valid?'Entrée active':s.alley.vip?'Entrée gratuite':`Entrée : ${s.alley.fee} Gold`,60,54.1,27,5,'art-paper guard-status');
   hit('Utiliser une invitation',7,74,44,12,()=>void run({action:'guard',key:'invite'},()=>{if(host.state().alley.access.valid)host.route('casino');}),s.alley.invitations===0);
   const enter=s.alley.access.valid?'Entrer dans la salle':s.alley.vip?'Entrer en VIP':`Payer ${s.alley.fee} Gold`;if(s.alley.access.valid||s.alley.vip||s.alley.fee!==150)value(enter,66,77.4,22,6.5,'guard-entry-label');
   hit(enter,53,74,39,12,()=>s.alley.access.valid?host.route('casino'):void run({action:'guard',key:'pay'},()=>{if(host.state().alley.access.valid)host.route('casino');}),!s.alley.access.valid&&!s.alley.vip&&s.balance.wallet<s.alley.fee);hit('Retour à la ruelle',35,87,30,8,back);
  }else if(kind==='robber'){
   value(`Votre réputation : ${s.alley.reputation.label}`,58,61.5,28,5.8,'art-paper art-small');
   hit('Planifier le braquage',6,76,52,14,()=>{planning=true;draw();});hit('Retour à la ruelle',60,76,33,14,back);
   if(planning){const dialog=el('section','art-extra robber-planning');dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label','Planifier le braquage');const content=el('div');alley(content,s);content.querySelector('.npc-portrait')?.remove();dialog.append(content,btn('Fermer',()=>{planning=false;draw();}));stage.append(dialog);for(const b of Array.from(stage.querySelectorAll<HTMLButtonElement>('.art-hit')))b.disabled=true;}
  }else{
   image.src='/assets/ui/merchant-scene.webp';image.classList.add('market-scene-image');
   const actions=el('div','market-original-actions');stage.append(actions);
   for(const [label,file,route] of [['Acheter','merchant-buy.webp','market:buy'],['Vendre','merchant-sell.webp','market:sell'],['Histoire','merchant-story.webp','market:story'],['Partir','merchant-leave.webp','hub']]){
    const b=document.createElement('button');b.className='market-original-button';b.setAttribute('aria-label',label);b.disabled=busy;b.onclick=()=>host.route(route);const art=new Image();art.src='/assets/ui/'+file;art.alt='';b.append(art);actions.append(b);
   }

  }
  if(message){const status=el('p','art-notice',message);status.setAttribute('role','status');panel.append(status);}
 }
 function marketHome(body:HTMLElement,s:Snapshot){
 const wallet=el('div','market-wallet');stat(wallet,'Portefeuille',`${s.balance.wallet} Gold`);body.append(wallet);
 const choices=el('div','market-choices');
 for(const [label,mode,description,icon] of [['Acheter','buy','Outils, sacs et fournitures','axe'],['Vendre','sell','Échangez vos ressources contre des Gold','resource'],['Histoire','story','Objets liés à votre aventure','story']]){
 const card=el('article','market-choice'),art=el('div','market-choice-art');art.append(icon==='axe'?equipmentArt('axe'):icon==='resource'?resourceArt('Bois de chêne')??equipmentArt('bag'):el('span','market-story-emblem','✦'));card.append(art,el('p','',description),btn(label,()=>host.route('market:'+mode)));choices.append(card);
 }body.append(choices);
 }
 function forge(body:HTMLElement,s:Snapshot){
 const keys=['axe','pickaxe','spear','bag'].filter(k=>s.catalog[k]);if(!keys.includes(selected))selected=keys[0];const rack=el('div','forge-rack');rack.setAttribute('aria-label','Équipement à améliorer');keys.forEach(key=>{const label=({axe:'Hache',pickaxe:'Pioche',spear:'Lance',bag:'Sac'} as Record<string,string>)[key],b=btn(label,()=>{selected=key;message='';draw();});b.classList.add('forge-tab');b.setAttribute('aria-pressed',String(selected===key));const icon=equipmentArt(key);icon.classList.add('forge-tool-icon');b.append(icon);rack.append(b);});body.append(rack);
 const owned=s.owned[selected],current=s.gear[selected+'_level'],next=current+1,max=next>5;const comparison=el('div','gear-comparison');for(const [label,t] of [['Équipement actuel',current],['Amélioration',Math.min(5,next)]] as const){const card=el('article','gear-panel'),art=el('div','gear-art');card.append(el('h3','',label));art.append(equipmentArt(selected,t));card.append(art,el('strong','gear-name',label==='Équipement actuel'&&!owned?'Non possédé':gearName(s,selected,t)??s.catalog[selected].name),el('p','gear-tier',max&&label==='Amélioration'?'Palier maximum':`Palier ${t}`));comparison.append(card);}body.append(comparison);
 const requirements=el('section','forge-recipe');requirements.append(el('h3','','Matériaux requis'));const recipe=(selected==='bag'?s.bag_recipes:s.recipes)[next]??{},cost=s.forge_gold[selected==='bag'?'bag':'tool'][next]??0,level=s.forge_levels[next]??0;const list=el('div','recipe-list');Object.entries(recipe).forEach(([name,qty])=>{const have=s.resources[name]??0,row=el('div','recipe-material'+(have>=qty?' enough':'')),art=resourceArt(name);if(art)row.append(art);row.append(el('span','',name),el('strong','',`${have} / ${qty}`));list.append(row);});requirements.append(list);if(!max){const stats=el('div','menu-stats');stat(stats,'Niveau requis',String(level));stat(stats,'Coût',`${cost} Gold`);stat(stats,'Portefeuille',`${s.balance.wallet} Gold`);requirements.append(stats);}else requirements.append(el('p','','Votre équipement a atteint son dernier palier.'));body.append(requirements);const actions=el('div','menu-actions');if(!owned)actions.append(btn('Aller au marché',()=>host.route('market')));else actions.append(btn('Améliorer',()=>void run({action:'upgrade',key:selected}),max||s.level<level||s.balance.wallet<cost||Object.entries(recipe).some(([n,q])=>(s.resources[n]??0)<q)));body.append(actions);
 }
 function drinks(body:HTMLElement,s:Snapshot){const grid=el('div','drinks-grid');s.tavern.drinks_catalog.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.className='drink-card';b.disabled=!d.available||busy;b.setAttribute('aria-label',d.name);b.setAttribute('aria-pressed',String(selected===d.key));b.title=d.name;const x=[104,550,994][i%3],y=i<3?144:493;b.append(assetSlice('/assets/menus/drinks.webp',x,y,445,345));b.onclick=()=>{selected=d.key;message='';draw();};grid.append(b);});body.append(grid);const status=el('div','drink-status');status.append(el('span','',s.tavern.label),el('span','',`${s.tavern.remaining_today} verre(s) disponible(s)`));if(s.tavern.cooldown_seconds>0){const c=el('span','drink-timer');c.dataset.deadline=String(Date.now()+s.tavern.cooldown_seconds*1000);status.append(c);}body.append(status);const order=el('div','menu-actions');order.append(btn('Commander',()=>void run({action:'drink',key:selected}),!s.tavern.drinks_catalog.find(d=>d.key===selected)?.available||s.tavern.remaining_today===0||s.tavern.cooldown_seconds>0));body.append(order);tick();}
 function alley(body:HTMLElement,s:Snapshot){const content=el('div','npc-conversation');content.append(portrait(kind,kind==='guard'?[60,205,735,485]:[78,305,670,358]));const text=el('section','npc-terms');content.append(text);body.append(content);
 if(kind==='guard'){text.append(el('h3','','Salle clandestine'),el('p','npc-status',s.alley.access.valid?'Accès accordé':s.alley.vip?'Entrée VIP':'Accès réservé'));if(s.alley.access.valid)text.append(el('p','','Votre entrée reste valable jusqu’à minuit.'));else text.append(el('p','',s.alley.vip?'Votre réputation vous permet d’entrer gratuitement.':`${s.alley.fee} Gold · entrée valable jusqu’à minuit.`));const actions=el('div','menu-actions');if(!s.alley.access.valid){actions.append(btn('Utiliser une invitation',()=>void run({action:'guard',key:'invite'},()=>{if(host.state().alley.access.valid)host.route('casino');}),s.alley.invitations===0),btn(s.alley.vip?'Entrer en VIP':'Payer l’entrée',()=>void run({action:'guard',key:'pay'},()=>{if(host.state().alley.access.valid)host.route('casino');}),!s.alley.vip&&s.balance.wallet<s.alley.fee));}else actions.append(btn('Entrer dans la salle',()=>host.route('casino')));text.append(actions);
 }else{text.append(el('h3','','Banque de IV'),el('p','',`Réputation : ${s.alley.reputation.label}`));if(s.alley.heist){text.append(el('p','',`${s.alley.heist.attempts_left} essais restants · ${s.alley.heist.code_length} chiffres distincts`));const label=el('label','heist-code','Combinaison du coffre'),input=document.createElement('input');input.type='text';input.inputMode='numeric';input.maxLength=s.alley.heist.code_length;input.value=guess;input.disabled=busy;input.setAttribute('aria-label','Combinaison du coffre');const confirm=btn('Essayer la combinaison',()=>void run({action:'heist_guess',guess},text=>{guess='';message=text;}),!/^(?!.*(.).*\1)\d{4}$/.test(guess));input.oninput=()=>{guess=input.value;confirm.disabled=busy||!/^(?!.*(.).*\1)\d{4}$/.test(guess);};label.append(input);text.append(label,confirm);}else{text.append(el('p','','Préparez votre opération, puis tentez de trouver la combinaison du coffre.'));text.append(btn('Commencer le braquage',()=>void run({action:'heist_start'}),s.alley.ban_remaining>0||!['Criminel','Seigneur de la Ruelle'].includes(s.alley.reputation.label)));}}}
 function profile(body:HTMLElement,s:Snapshot){const identity=el('section','profile-identity'),avatar=el('div','profile-avatar',(s.discord?.display_name??s.name).slice(0,2).toUpperCase());if(s.discord?.avatar_url){const img=new Image();img.alt='Avatar Discord de '+s.discord.display_name;img.src=s.discord.avatar_url;img.onerror=()=>img.remove();avatar.append(img);}const title=el('div','profile-title');title.append(el('h3','',s.name),el('p','',s.discord?s.discord.display_name:'Aventurier de Legacy'),el('span','profile-level',`Niveau ${s.level}`));identity.append(avatar,title);const xp=el('div','profile-xp'),bar=document.createElement('progress');bar.max=s.xp_needed;bar.value=s.xp;bar.setAttribute('aria-label','Expérience');xp.append(el('span','',`${s.xp} / ${s.xp_needed} XP`),bar);identity.append(xp);body.append(identity);const tabs=el('div','menu-tabs');['Résumé','Équipement','Inventaire'].forEach(label=>{const b=btn(label,()=>{profileTab=label;inventoryPage=0;draw();});b.setAttribute('aria-pressed',String(profileTab===label));tabs.append(b);});body.append(tabs);
 if(profileTab==='Résumé'){const stats=el('div','profile-stats');for(const [label,v] of [['Portefeuille',s.balance.wallet+' Gold'],['Banque',s.balance.bank+' Gold'],['Fortune',s.balance.wallet+s.balance.bank+' Gold'],['Victoires',String(s.stats.wins??0)],['Défaites',String(s.stats.losses??0)],['Expéditions',String(s.stats.expeditions??0)]])stat(stats,label,v);body.append(stats);const status=el('div','profile-activities');status.append(el('p','',`Réputation dans la ruelle : ${s.alley.reputation.label}`),el('p','',`Taverne : ${s.tavern.label}`),el('p','',`Histoire : ${s.chapters.filter(c=>c.unlocked).length} / ${s.chapters.length} chapitres`),el('p','',s.active?'Expédition : '+s.active.name:'Aucune expédition en cours.'),el('p','',s.pending?'Mission : '+s.pending.job.title:'Aucune mission en cours.'));body.append(status);
 }else if(profileTab==='Équipement'){const grid=el('div','profile-gear');Object.keys(s.catalog).forEach(key=>{const c=el('article','profile-gear-item');c.append(equipmentArt(key,s.gear[key+'_level']),el('h3','',gearName(s,key,s.gear[key+'_level'])??s.catalog[key].name),el('p','',s.owned[key]?'Palier '+s.gear[key+'_level']:'Non possédé'));grid.append(c);});body.append(grid);}else{const storyNames=new Set(s.owned_story_items.map(i=>i.name));const entries=Object.entries(s.resources).filter(([name,qty])=>qty>0&&!storyNames.has(name)),last=Math.max(0,Math.ceil(entries.length/4)-1);inventoryPage=Math.min(last,inventoryPage);body.append(el('h3','','Ressources'));const grid=el('div','profile-inventory');entries.slice(inventoryPage*4,inventoryPage*4+4).forEach(([name,qty])=>{const c=el('div','profile-resource'),art=resourceArt(name);if(art)c.append(art);c.append(el('span','',name),el('strong','',String(qty)));grid.append(c);});body.append(grid);if(!entries.length)body.append(el('p','','Votre sac est vide.'));else{const pager=el('div','menu-actions');pager.append(btn('Précédent',()=>{inventoryPage--;draw();},inventoryPage===0),el('span','',`${inventoryPage+1} / ${last+1}`),btn('Suivant',()=>{inventoryPage++;draw();},inventoryPage===last));body.append(pager);}const histories=s.owned_story_items;const story=el('section','profile-story-items');story.append(el('h3','','Objets d’histoire'));if(histories.length)histories.forEach(i=>story.append(el('p','',i.name.replace(/^[^\p{L}\p{N}]+/u,''))));else story.append(el('p','','Aucun objet d’histoire acquis.'));body.append(story);}}
 function world(body:HTMLElement,s:Snapshot){
  const sheet=el('div','elyndor-atlas');const image=new Image();image.src='/assets/scenes/elyndor-map-clean.png';image.alt='Le monde d’Elyndor : Altherya, Elarwyn, Vorak, la Forge de Khaz’goram et la Tour d’Ashkar.';sheet.append(image);
  const places=[{key:'hub',name:'Altherya',x:39,y:46,w:18,h:6.8,level:1},{key:'elarwyn',name:'Forêt d’Elarwyn',x:17,y:42,w:19,h:7.2,level:1},{key:'vorak',name:'Mont Vorak',x:69,y:49,w:18,h:6.8,level:1},{key:'khaz',name:'Forge de Khaz’goram',x:46,y:25,w:22,h:7.1,level:3},{key:'ashkar',name:'Tour d’Ashkar',x:78,y:26,w:18,h:6.8,level:5}];
  for(const place of places){const locked=s.level<place.level;const label=place.name+(locked?' · Niveau '+place.level:'');const hit=document.createElement('button');hit.type='button';hit.className='atlas-place atlas-image'+(locked?' locked':'');hit.style.cssText=`left:${place.x}%;top:${place.y}%;width:${place.w}%;height:${place.h}%`;hit.setAttribute('aria-label','Voyager vers '+label);hit.title=label;hit.disabled=locked;hit.onclick=()=>host.route(place.key);hit.dataset.destination=place.key;hit.append(worldButtonArt(place.key));if(locked)hit.append(el('span','atlas-lock','Niv. '+place.level));sheet.append(hit);}
  const back=document.createElement('button');back.type='button';back.className='atlas-place atlas-return';back.setAttribute('aria-label','Retour en ville');back.append(el('span','atlas-label','Retour en ville'));back.onclick=()=>host.route('hub');sheet.append(back);body.append(sheet);
 }
 function worldEntrance(body:HTMLElement,s:Snapshot){
  const tower=kind==='ashkar',required=tower?5:3;const hero=el('div','world-entry-art '+kind);hero.setAttribute('role','img');hero.setAttribute('aria-label',titles[kind]);body.append(hero);
  const intro=el('div','world-entry-copy');intro.append(el('h3','',tower?'Osez gravir les étages':'Le métal façonne les légendes'),el('p','',tower?'L’entrée de la Tour d’Ashkar. Trois étages par jour, un gardien à chaque palier et un boss au sommet.':'La forge géante de Khaz’goram, domaine du maître forgeron Thorgar.'));
  intro.append(el('p','',s.level>=required?'Accès débloqué · Niveau '+s.level:'Accès à partir du niveau '+required));
  intro.append(el('p','world-entry-note',tower?'Les combats de la Tour doivent encore être reliés à l’Activity.':'L’atelier d’équipement de Thorgar doit encore être relié à l’Activity.'));body.append(intro);
 }
 function read(n:number){chapter=n;message='';if(texts.has(n)){draw();return;}void run({action:'story_read',chapter:n},text=>texts.set(n,text));}
 function story(body:HTMLElement,s:Snapshot){const available=s.chapters.filter(c=>c.unlocked);if(!available.some(c=>c.chapter===chapter))chapter=available[0]?.chapter??1;const index=available.findIndex(c=>c.chapter===chapter),current=available[index];const book=el('article','chronicle-book');body.append(book);const indexPage=el('div','book-index');indexPage.append(el('p','book-kicker','Chroniques d’Altherya'),el('h3','','Saison I'),el('p','',`${available.length} chapitre(s) débloqué(s)`));const list=el('div','book-chapters');available.forEach(c=>{const b=document.createElement('button');b.type='button';b.textContent=String(c.chapter).padStart(2,'0')+' · '+c.title;b.disabled=busy;b.setAttribute('aria-label','Lire le chapitre '+c.chapter);b.setAttribute('aria-current',String(c.chapter===chapter));b.onclick=()=>read(c.chapter);list.append(b);});indexPage.append(list);book.append(indexPage);const paper=el('section','book-page');paper.setAttribute('aria-label','Chapitre '+chapter);paper.append(el('p','book-kicker','Chapitre '+chapter),el('h3','book-chapter-title',current?.title??'Chroniques'));const prose=el('div','book-prose');prose.setAttribute('tabindex','0');prose.setAttribute('aria-label','Récit du chapitre '+chapter);const text=texts.get(chapter);if(text)text.split(/\n\s*\n/).forEach(p=>prose.append(el('p','',p)));else prose.append(el('p','',busy?'Le troubadour ouvre son livre…':'Ouvrez ce chapitre pour écouter le récit.'));paper.append(prose,el('span','book-folio',String(chapter)));book.append(paper);const navigation=el('div','menu-actions book-navigation');navigation.append(btn('Chapitre précédent',()=>read(available[index-1].chapter),index<=0),el('span','',`${index+1} / ${available.length}`),btn('Chapitre suivant',()=>read(available[index+1].chapter),index>=available.length-1));body.append(navigation);const next=s.chapters.find(c=>!c.unlocked);if(next){const unlock=el('div','book-unlock');unlock.append(el('p','',next.missing.length?'Objets nécessaires au prochain chapitre : '+next.missing.map(n=>n.replace(/^[^\p{L}\p{N}]+/u,'')).join(', '):'Votre prochain chapitre est prêt à être débloqué.'));unlock.append(btn('Débloquer le chapitre',()=>void run({action:'story_unlock',chapter:next.chapter},text=>{if(host.state().chapters.find(c=>c.chapter===next.chapter)?.unlocked){chapter=next.chapter;texts.delete(chapter);queueMicrotask(()=>read(chapter));}else message=text;}),!next.can_unlock));body.append(unlock);}}
 function tick(){panel.querySelectorAll<HTMLElement>('.drink-timer[data-deadline]').forEach(n=>{const t=Math.max(0,Math.ceil((Number(n.dataset.deadline)-Date.now())/1000));fieldText(n,t?'Service dans '+timeLabel(t):'Service disponible');});}
 const stopSize=watchMenuSize(panel);const clock=window.setInterval(tick,1000);trapMenu(panel,()=>busy,host.close);draw();panel.scrollTop=0;panel.querySelector<HTMLButtonElement>('.menu-header button')?.focus({preventScroll:true});if(kind==='story')read(chapter);
 return{destroy(){dead=true;stopSize();clearInterval(clock);panel.onkeydown=null;document.body.classList.remove('illustrated-open');},update(){if(!busy&&!(document.activeElement instanceof HTMLInputElement&&panel.contains(document.activeElement)))draw();}};
}
