import type {Snapshot} from '../activity';
import {withdrawalQuote,validAmount,pageSlice} from './service-model';
import './services.css';
type Host={state:()=>Snapshot;mutate:(body:Record<string,unknown>)=>Promise<string>;close:()=>void;route:(key:string)=>void};
const motifs:Record<string,string>={bank:'◆',forge:'⚒',jobs:'✉',profile:'♜',castle:'♛',story:'♫',expedition:'✦',world:'✧',journal:'☷'};
export function openService(panel:HTMLElement,kind:string,host:Host,location='elarwyn',customTitle=''){
 let page=0,selected='',mode='deposit',amount=1,step=0,tool='hands',accessories=['none','none'],locked=false,notice='',deadline=0;
 const titles:Record<string,string>={bank:'Banque de Legacy',forge:'La forge',jobs:'Petites annonces',profile:'Votre personnage',castle:'Le château',story:'Le troubadour',expedition:'Les expéditions',world:'Terres d’Elyndor',journal:'Journal d’aventure'};
 const el=(tag:string,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
 const btn=(text:string,fn:()=>void,disabled=false)=>{const b=el('button',text,'service-button') as HTMLButtonElement;b.disabled=disabled||locked;b.onclick=fn;return b;};
 async function run(body:Record<string,unknown>,after?:()=>void){if(locked)return;locked=true;draw();try{notice=await host.mutate(body);after?.();return true;}catch(e){notice=String(e);return false;}finally{locked=false;draw();}}
 function card(parent:HTMLElement,title:string,text:string){const c=el('article','','service-card');c.append(el('h3',title),el('p',text));parent.append(c);return c;}
 function pager(parent:HTMLElement,count:number){page=Math.min(page,Math.max(0,Math.ceil(count/4)-1));const bar=el('div','','service-controls');bar.append(btn('◀ Précédent',()=>{page--;draw();},page===0),el('span',`${page+1} / ${Math.max(1,Math.ceil(count/4))}`),btn('Suivant ▶',()=>{page++;draw();},(page+1)*4>=count));parent.append(bar);}
 function draw(){const s=host.state();panel.className='service-panel service-'+kind;panel.hidden=false;panel.replaceChildren();const header=el('header','','service-header');header.append(el('span',motifs[kind]??'◆','service-seal'),el('h2',customTitle||titles[kind]||kind));panel.append(header);const body=el('div','','service-body');panel.append(body);if(notice){const n=el('p',notice,'service-notice');n.setAttribute('role','status');body.append(n);}const grid=el('div','','service-grid');
 if(kind==='bank'){
 const ledger=el('div','','service-ledger');for(const [name,value] of [['Bourse',s.balance.wallet],['Coffre',s.balance.bank],['Fortune',s.balance.wallet+s.balance.bank]])card(ledger,String(name),`${value} Gold`);body.append(ledger);const tabs=el('div','','service-controls');for(const m of ['deposit','withdraw'])tabs.append(btn(m==='deposit'?'Déposer au coffre':'Retirer du coffre',()=>{mode=m;amount=1;notice='';draw();},mode===m));body.append(tabs);
 const max=mode==='deposit'?s.balance.wallet:s.balance.bank;const c=card(body,mode==='deposit'?'Bordereau de dépôt':'Bordereau de retrait',`Disponible : ${max} Gold`);const controls=el('div','','service-controls');const input=document.createElement('input');input.type='number';input.min='1';input.max=String(max);input.value=String(amount);input.setAttribute('aria-label','Montant en Gold');const quote=el('p','','service-quote');const confirm=btn('Confirmer le transfert',()=>void run({action:mode,amount}));function preview(){const q=withdrawalQuote(amount,s.balance.free_withdrawal_available);quote.textContent=mode==='deposit'?`Au coffre après dépôt : ${s.balance.bank+amount} Gold`:`Frais : ${q.fee} Gold · Reçu : ${q.received} Gold${s.balance.free_withdrawal_available?' · Premier retrait gratuit':''}`;confirm.disabled=locked||!validAmount(amount,max);}input.oninput=()=>{amount=Number(input.value);preview();};controls.append(input,...[100,500,max].filter((v,i,a)=>v>0&&v<=max&&a.indexOf(v)===i).map(v=>btn(v===max?'Tout':String(v),()=>{amount=v;input.value=String(v);preview();})));c.append(controls,quote,confirm);preview();
 }else if(kind==='jobs'){
 if(s.pending){const p=s.pending;if(!deadline)deadline=Date.now()+p.remaining*1000;const c=card(body,p.job.title,`Récompense : ${p.job.reward} Gold · Contrat en cours`);c.append(el('p','','service-countdown'),btn('Récupérer la récompense',()=>void run({action:'job_claim'},()=>{deadline=0;}),!p.ready));}else{deadline=0;pager(body,s.board.jobs.length);const labels:Record<string,string>={common:'Commun',uncommon:'Peu commun',rare:'Rare',epic:'Épique',legendary:'Légendaire'};pageSlice(s.board.jobs,page).forEach(j=>{const c=card(grid,j.title,`${labels[j.rarity]??j.rarity} · ${j.reward} Gold · Durée : 1 heure`);c.classList.add('service-contract');c.append(btn(selected===j.job_id?'Signer ce contrat':'Examiner le contrat',()=>{if(selected===j.job_id)void run({action:'job_accept',key:j.job_id,batch:s.board.batch_id},()=>{selected='';deadline=0;});else{selected=j.job_id;draw();}}));});body.append(grid);}
 }else if(kind==='expedition'){
 if(s.active){if(!deadline)deadline=Date.now()+s.active.remaining*1000;const c=card(body,s.active.name,'Expédition en cours. Les gains seront ajoutés à votre retour.');c.append(el('div','◆ ━━━━━ ✦ ━━━━━ ⚑','service-journey'),el('p','','service-countdown'));}else{deadline=0;const ds=Object.entries(s.destinations).filter(([,d])=>d.location_key===location);body.append(el('p',`Préparation · Étape ${step+1} / 3`,'service-step'));if(step===0){pager(body,ds.length);pageSlice(ds,page).forEach(([key,d])=>{const c=card(grid,d.name,`Niveau ${d.level} · ${d.duration_label}`);c.append(btn('Préparer cette destination',()=>{selected=key;tool=d.tools[0];step=1;draw();},s.level<d.level));});body.append(grid);}else{const d=s.destinations[selected];if(!d){step=0;draw();return;}const c=card(body,d.name,d.duration_label);if(step===1){c.append(el('p','Votre meilleur outil et votre meilleur sac seront utilisés.'));d.tools.forEach(t=>c.append(btn(t==='hands'?'Mains nues':s.tools[s.gear[t+'_level']][t],()=>{tool=t;step=2;draw();},t!=='hands'&&(!s.owned[t]||!s.owned.bag))));c.append(btn('Autre destination',()=>{step=0;draw();}));}else{for(let slot=0;slot<2;slot++){const group=el('div','','service-accessories');group.append(el('h3',`Accessoire ${slot+1} · ${s.objects[accessories[slot]].name}`));Object.entries(s.objects).forEach(([id,o])=>group.append(btn(o.name,()=>{accessories[slot]=id;draw();},accessories[slot]===id||(id!=='none'&&accessories[1-slot]===id))));c.append(group);}c.append(el('p',`Outil : ${tool==='hands'?'Mains nues':s.tools[s.gear[tool+'_level']][tool]} · Durée : ${d.duration_label}`),btn('Confirmer le départ',()=>void run({action:'start',key:selected,tool,object1:accessories[0],object2:accessories[1]},()=>{step=0;deadline=0;})),btn('Changer d’outil',()=>{step=1;draw();}));}}}
 }else if(kind==='castle'){
 const c=card(body,'Audience quotidienne','200 Gold et 20 XP · Renouvellement à minuit, heure du serveur.');c.append(btn(s.daily_available?'Recevoir la récompense':'Récompense déjà reçue',()=>void run({action:'daily'}),!s.daily_available));body.append(btn('Votre personnage',()=>host.route('profile')),btn('Journal d’aventure',()=>host.route('journal')));
 }else if(kind==='journal'){
 const c=card(body,'Vos activités',s.active?'Voyage : '+s.active.name:'Aucune expédition en cours.');c.append(el('p',s.pending?'Contrat : '+s.pending.job.title:'Aucun contrat en cours.'),el('p',`Histoire : ${s.chapters.filter(ch=>ch.unlocked).length} / ${s.chapters.length} chapitres débloqués.`));body.append(btn('Petites annonces',()=>host.route('jobs')),btn('Expéditions',()=>host.route('expedition')),btn('Le troubadour',()=>host.route('story')));card(body,'Objectifs quotidiens et gazette','Ces fonctions du bot restent à intégrer dans l’Activity.');
 }else card(body,customTitle||'Prochainement','Cette fonction du bot reste à intégrer dans l’Activity.');
 body.append(btn('Retour en ville',()=>host.route('hub'),locked));if(locked){body.setAttribute('aria-busy','true');body.append(el('p','Opération en cours…','service-notice'));}tick();}
 function tick(){panel.querySelectorAll('.service-countdown').forEach(n=>{const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));n.textContent=remaining?`Retour dans ${Math.floor(remaining/3600)} h ${Math.floor(remaining%3600/60)} min ${remaining%60} s`:'Terminé · Synchronisation avec le serveur…';});}
 const clock=window.setInterval(tick,1000);panel.onkeydown=e=>{if(e.key==='Escape'&&!locked){e.preventDefault();host.close();}if(e.key==='Tab'){const nodes=Array.from(panel.querySelectorAll<HTMLElement>('button:not(:disabled),input'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};draw();panel.querySelector<HTMLElement>('button')?.focus();return {destroy(){clearInterval(clock);panel.onkeydown=null;},update(){if(kind==='bank'&&document.activeElement instanceof HTMLInputElement)return;deadline=0;draw();}};
}
