/* PC/mobile checks for exclusive menus, confirmations, input and transitions. */
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../../..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'altherya-layers-')),db=path.join(tmp,'state.db'),port=process.env.TEST_LAYER_PORT||'8108',url='http://127.0.0.1:'+port,shots=process.env.SCREENSHOTS_DIR||path.join(tmp,'shots');fs.mkdirSync(shots,{recursive:true});
(async()=>{const server=spawn('python3',['apps/api/server.py'],{cwd:root,env:{...process.env,PORT:port,ACTIVITY_DB:db},stdio:'ignore'});let browser;const errors=[];let checks=0;
try{for(let i=0;i<80;i++){try{if((await fetch(url+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:JSON.parse(process.env.CHROMIUM_ARGS||'[]')});const context=await browser.newContext();
for(const [device,viewport] of [['pc',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){await context.clearCookies();const p=await context.newPage();await p.setViewportSize(viewport);p.on('pageerror',e=>errors.push(String(e)));const click=label=>p.locator('#panel').getByRole('button',{name:label,exact:true}).click(),hub=async()=>{await p.reload();await p.locator('#scene-stage[data-scene="hub"][aria-busy="false"]').waitFor();},one=async modal=>{await p.waitForFunction(expected=>!document.querySelector('#panel').hidden&&document.querySelector('#panel').hasAttribute('data-modal-open')===expected,modal);assert.equal(await p.getByRole('dialog').count(),1);assert.ok(await p.locator('#scene-stage').evaluate(n=>n.inert));for(const b of await p.locator('#scene-stage button').all())assert.ok(!await b.isVisible());checks++;},shot=async name=>{await p.screenshot({path:path.join(shots,name+'-'+device+'.png')});};
await p.goto(url);await p.getByRole('textbox',{name:'Nom du personnage'}).fill('Menus');await click('Entrer dans Legacy');await p.locator('#panel').waitFor({state:'hidden'});execFileSync('python3',['-c',`import sqlite3;c=sqlite3.connect(${JSON.stringify(db)});c.execute('UPDATE players SET wallet_gold=10000');c.commit()`]);await hub();
await p.getByRole('button',{name:'Marché',exact:true}).click();await one(false);assert.equal(await p.locator('.market-toolbar').count(),0);await click('Acheter');await one(false);await p.locator('.merchant-card').first().getByRole('button',{name:'Acheter',exact:true}).click();await one(true);assert.ok(!await p.locator('.merchant-header').isVisible());assert.ok(!await p.locator('.merchant-grid').isVisible());await shot('market-confirm');await p.keyboard.press('Escape');await one(false);assert.ok(await p.locator('.merchant-grid').isVisible());await click('Retour au marché');await click('Partir');await p.locator('#panel').waitFor({state:'hidden'});await p.locator('#scene-stage[data-scene="hub"][aria-busy="false"]').waitFor();assert.ok(await p.locator('#scene-stage').evaluate(n=>!n.inert));checks++;
await p.getByRole('button',{name:'Ruelle sombre',exact:true}).click();await click('Le braqueur');await p.locator('.scene-actionbar').getByRole('button',{name:'Planifier un braquage',exact:true}).click();await one(false);assert.ok(!await p.locator('.scene-actionbar').isVisible());await shot('robber-single');assert.equal(await p.getByRole('button',{name:/^Fermer/}).count(),0);await p.keyboard.press('Escape');await p.locator('#panel').waitFor({state:'hidden'});assert.ok(await p.locator('.scene-actionbar').isVisible());await p.locator('.scene-actionbar').getByRole('button',{name:'Retour à la ruelle',exact:true}).click();await click('Le vigile');await p.locator('.scene-actionbar').getByRole('button',{name:'Parler au vigile',exact:true}).click();await one(false);await click('Payer l’entrée');await p.locator('#panel[data-kind="casino"]').waitFor();await click('Roulette');await p.locator('#panel[data-kind="roulette"]').waitFor();await one(false);
await p.getByRole('button',{name:'Règles',exact:true}).evaluate(b=>{b.click();b.click();});await one(true);assert.equal(await p.locator('.game-help-overlay').count(),1);assert.ok(!await p.locator('.game-table').isVisible());await shot('rules-single');await p.keyboard.press('Escape');await one(false);assert.ok(await p.locator('.game-table').isVisible());assert.ok(await p.locator('.game-table').evaluate(n=>!n.inert));await click('Manches récentes');await one(true);await click('Revenir au jeu');await one(false);checks++;
await hub();await p.getByRole('button',{name:'Petites annonces',exact:true}).click();await p.locator('#panel').getByRole('button',{name:/^Accepter /}).first().click();await one(true);assert.ok(!await p.locator('.compact-dock').isVisible());assert.ok(!await p.locator('.menu-heading').isVisible());await shot('contract-single');await click('Revenir aux annonces');await one(false);assert.ok(await p.locator('.compact-dock').isVisible());
await hub();await p.getByRole('button',{name:'Arène',exact:true}).click();await click('Affronter le champion');await one(true);assert.ok(!await p.locator('.compact-dock').isVisible());await shot('champion-single');await click('Retour');await one(false);
await hub();let release;const wait=new Promise(r=>release=r);await p.route('**/assets/scenes/bank.webp',async route=>{await wait;await route.continue();});await p.getByRole('button',{name:'Banque',exact:true}).click();await p.locator('#scene-stage[aria-busy="true"]').waitFor();await p.waitForFunction(()=>document.querySelector('#scene-stage').inert);await p.keyboard.press('i');assert.ok(await p.locator('#panel').isHidden());release();await p.locator('#panel[data-kind="bank"]').waitFor();await one(false);await p.unroute('**/assets/scenes/bank.webp');assert.equal(await p.getByRole('button',{name:/^Fermer/}).count(),0);await p.keyboard.press('Escape');await p.locator('#scene-stage[data-scene="hub"][aria-busy="false"]').waitFor();assert.equal(await p.locator('#panel .compact-dock').count(),0);assert.ok(await p.locator('#panel').isHidden());checks++;await p.close();}
assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors,screenshots:shots}));}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
