/* Run from apps/game: node tests/browser-games.cjs. Requires built client, API deps and Playwright Chromium. */
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,execFileSync}=require('node:child_process');
const app=path.resolve(__dirname,'..'),root=path.resolve(app,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'altherya-games-')),db=path.join(temp,'test.sqlite3'),shots=process.env.SCREENSHOTS_DIR||path.join(temp,'screenshots'),port=process.env.TEST_GAME_PORT||'8096',url='http://127.0.0.1:'+port;fs.mkdirSync(shots,{recursive:true});
(async()=>{const server=spawn('python3',['apps/api/server.py'],{cwd:root,env:{...process.env,PORT:port,ACTIVITY_DB:db},stdio:'ignore'});let browser;try{for(let i=0;i<60;i++){try{if((await fetch(url+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:JSON.parse(process.env.CHROMIUM_ARGS||'[]')});const context=await browser.newContext(),errors=[];let checks=0;
for(const [size,viewport] of [['pc',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){await context.clearCookies();const p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.setViewportSize(viewport);await p.goto(url);await p.getByRole('textbox',{name:'Nom du personnage'}).fill('IV');await p.getByRole('button',{name:'Entrer dans Legacy'}).click();await p.locator('#panel').waitFor({state:'hidden'});execFileSync('python3',['-c',`import sqlite3;c=sqlite3.connect(${JSON.stringify(db)});c.execute('UPDATE players SET wallet_gold=10000');c.commit()`]);await p.reload();await p.locator('#scene-stage[data-scene="hub"][aria-busy="false"]').waitFor();
const click=async label=>p.locator('#panel').getByRole('button',{name:label,exact:true}).click(),state=async()=>p.evaluate(async()=>(await(await fetch('/api/activity')).json()).state),settled=async()=>p.locator('#panel[aria-busy="false"]').waitFor({timeout:15000});
await p.getByRole('button',{name:'Ruelle sombre',exact:true}).click();await click('Le vigile');await p.locator('.scene-actionbar').getByRole('button',{name:'Parler au vigile',exact:true}).click();await click('Payer 150 Gold');await p.locator('#panel[data-kind="casino"]').waitFor();
const cases=[['blackjack','Black Jack','Distribuer'],['roulette','Roulette','Lancer la roulette'],['slots','Machine à sous','Actionner le levier'],['horses','Courses','Lancer la course'],['russian','Roulette russe','Commencer'],['dice','Lancer de dés','Jouer'],['coin','Pile ou face','Jouer'],['rps','Pierre feuille ciseaux','Jouer']];
for(const [kind,label,start] of cases){if(kind==='dice'){await click('Quitter la salle');await p.locator('.scene-actionbar').getByRole('button',{name:'Retour à la ruelle',exact:true}).click();await click('Retour en ville');await p.getByRole('button',{name:'Taverne',exact:true}).click();await click('Les jeux');}
await click(label);await p.locator('#panel.live-game[data-kind="'+kind+'"]').waitFor();await click('Règles');assert.ok(await p.locator('.game-help p').count());await p.keyboard.press('Escape');await p.locator('.game-help').waitFor({state:'detached'});
const wager=p.getByRole('spinbutton');for(const value of ['0','.5','100000']){await wager.fill(value);assert.ok(await p.locator('[data-start]').first().isDisabled());}await wager.fill('10');await p.getByRole('button',{name:'Augmenter la mise',exact:true}).click();assert.equal(await wager.inputValue(),'20');await p.getByRole('button',{name:'Diminuer la mise',exact:true}).click();assert.equal(await wager.inputValue(),'10');await click('50');assert.equal(await wager.inputValue(),'50');await click('10');
if(kind==='roulette'){assert.equal(await p.locator('.roulette-numbers button').count(),37);await click('Choisir un numéro');await click('Numéro 17');}
const before=await state();await click(start);await p.locator('.game-table[data-animating="true"]').waitFor();assert.ok(await p.getByRole('button',{name:'Retour',exact:true}).isDisabled());const anims=await p.locator('.game-table').evaluate(n=>n.getAnimations({subtree:true}).length);assert.ok(anims>0||kind==='horses');await p.screenshot({path:path.join(shots,kind+'-'+size+'-during.png')});await settled();
if(kind==='blackjack'){if(await p.getByRole('button',{name:'Tirer une carte',exact:true}).count()){await click('Tirer une carte');await settled();}if(await p.getByRole('button',{name:'Rester',exact:true}).count()){await click('Rester');await settled();}}
if(kind==='russian'){for(let i=0;i<4&&await p.getByRole('button',{name:'Tenter',exact:true}).count();i++){await click('Tenter');await settled();}}
const after=await state(),play=after.play;assert.equal(play.status,'finished');assert.equal(after.balance.wallet,before.balance.wallet-10+play.payout);assert.equal(await p.locator('.game-result').getAttribute('data-outcome'),play.payout>10?'win':play.payout===10?'tie':'loss');
if(kind==='roulette')assert.ok((await p.locator('.game-result').innerText()).includes('Numéro '+play.number));
if(kind==='slots'){const key={'🍒':'cherry','🔔':'bell','💎':'diamond','👑':'crown','7️⃣':'seven'};assert.deepEqual(await p.locator('.live-reel').evaluateAll(ns=>ns.map(n=>n.dataset.symbol)),play.reels.map(r=>key[r]));}
if(kind==='dice')assert.deepEqual(await p.locator('.game-die').evaluateAll(ns=>ns.map(n=>n.querySelectorAll('circle').length)),[play.player,play.opponent]);
if(kind==='coin')assert.equal(await p.locator('.game-coin-token svg').getAttribute('data-face'),play.opponent);
if(kind==='rps'){const key={pierre:'rock',feuille:'paper',ciseaux:'scissors'};assert.deepEqual(await p.locator('.rps-side svg').evaluateAll(ns=>ns.map(n=>n.dataset.gesture)),[key[play.player],key[play.opponent]]);}
if(kind==='horses'){const positions=await p.locator('[data-runner]').evaluateAll(ns=>ns.map(n=>parseFloat(n.style.left)));assert.equal(positions.indexOf(Math.max(...positions)),play.winner);}
assert.ok(await p.locator('.game-table').evaluate(n=>n.scrollWidth<=n.clientWidth+2));await p.screenshot({path:path.join(shots,kind+'-'+size+'.png')});await click('Manches récentes');assert.ok(await p.locator('.game-receipt').count());await click('Revenir au jeu');await click('Retour');await p.locator('#panel[data-kind="'+(['dice','coin','rps'].includes(kind)?'games':'casino')+'"]').waitFor();checks++;
}
// A refused request must unlock controls and leave the real wallet unchanged.
await click('Pile ou face');const before=await state();await p.route('**/api/activity',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().action==='game_start')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Erreur réseau de test'})});else await route.continue();});await p.locator('[data-start]').first().click();await settled();assert.equal((await state()).balance.wallet,before.balance.wallet);assert.ok(!await p.locator('[data-start]').first().isDisabled());await p.unroute('**/api/activity');await click('Retour');
await p.emulateMedia({reducedMotion:'reduce'});await click('Lancer de dés');await p.locator('[data-start]').first().click();await settled();assert.ok(!await p.locator('[data-start]').first().isDisabled());checks+=2;await p.close();}
assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors,screenshots:shots}));}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
