import {test} from 'node:test';
import assert from 'node:assert/strict';
import {products,resourceCategory,pageItems,clampQuantity,tradeBlock,tradeBody} from '../src/ui/commerce-model';
import type {Snapshot} from '../src/activity';
const state={catalog:{axe:{name:'Hache en bois',price:400},spear:{name:'Lance en bois',price:400},pickaxe:{name:'Pioche en bois',price:400},bag:{name:'Sac de fortune',price:400}},owned:{axe:false,spear:false,pickaxe:true,bag:false},bags:{'1':{name:'Sac de fortune'}},story_items:[{name:'Relique',chapter:2,price:500,owned:false}],balance:{wallet:450,bank:0,free_withdrawal_available:true},resources:{'Bois de chêne':12,'Minerai de fer':5,'Peau de loup':3,'Champignon commun':2,'Relique':1,'Pierre brute':0},prices:{'Bois de chêne':2,'Minerai de fer':5,'Peau de loup':6,'Champignon commun':2}} as unknown as Snapshot;
test('les rayons utilisent les vrais équipements et objets d’histoire sans consommables inventés',()=>{const list=products(state,'buy');assert.equal(list.length,4);assert.equal(list.filter(p=>p.category==='Outils').length,3);assert.equal(list.filter(p=>p.category==='Consommables').length,0);assert.equal(list.find(p=>p.key==='bag')?.category,'Divers');assert.equal(list.find(p=>p.key==='pickaxe')?.owned,true);assert.equal(products(state,'story')[0].key,'Relique');assert.ok(!list.some(p=>p.icon==='scroll'));assert.equal(list.filter(p=>p.category==='Divers').length,1);});
test('les ventes séparent les trois métiers et excluent les objets non vendables ou épuisés',()=>{assert.equal(resourceCategory('Minerai de fer'),'Mineur');assert.equal(resourceCategory('Peau de loup'),'Chasseur');assert.equal(resourceCategory('Bois de chêne'),'Bûcheron');assert.equal(resourceCategory('Champignon commun'),'Bûcheron');const list=products(state,'sell');assert.equal(list.length,4);assert.ok(!list.some(p=>p.key==='Relique'));assert.ok(!list.some(p=>p.stock===0));});
test('les quantités restent entières et dans les limites du stock',()=>{for(const [value,expected] of [[-3,1],[0,1],[4.9,4],[100,12],[NaN,1],[Infinity,1]])assert.equal(clampQuantity(value,12),expected);});
test('quatre objets par page, sans perte ni débordement',()=>{const sample=products(state,'buy')[0];const list=Array.from({length:9},(_,i)=>({...sample,key:String(i)}));assert.equal(pageItems(list,0).items.length,4);assert.equal(pageItems(list,1).items.length,4);assert.equal(pageItems(list,2).items.length,1);assert.equal(pageItems(list,-1).page,0);assert.equal(pageItems(list,10).page,2);assert.deepEqual([0,1,2].flatMap(page=>pageItems(list,page).items),list);assert.equal(pageItems([],2).last,0);});
test('les confirmations adressent uniquement l’objet et la quantité au serveur',()=>{const list=products(state,'buy');const axe=list.find(p=>p.key==='axe')!;const relic=products(state,'story')[0];assert.deepEqual(tradeBody(axe,'buy',1),{action:'buy',key:'axe'});assert.deepEqual(tradeBody(relic,'story',1),{action:'story_buy',key:'Relique'});const wood=products(state,'sell')[0];assert.deepEqual(tradeBody(wood,'sell',50),{action:'sell',key:'Bois de chêne',amount:12});});
test('le bouton bloque SOLD OUT, le découvert et les stocks insuffisants',()=>{const list=products(state,'buy');assert.equal(tradeBlock(list.find(p=>p.key==='pickaxe'),'buy',450,1),'SOLD OUT');assert.equal(tradeBlock(list.find(p=>p.key==='axe'),'buy',399,1),'Gold insuffisant');assert.equal(tradeBlock(list.find(p=>p.key==='axe'),'buy',400,1),'');assert.equal(tradeBlock(products(state,'sell')[0],'sell',0,13),'Stock insuffisant');});

test('le chapitre serveur accompagne les objets d’histoire et reste absent des autres rayons',()=>{assert.equal(products(state,'story')[0].chapter,2);assert.ok(products(state,'buy').every(p=>p.chapter===undefined));assert.ok(products(state,'sell').every(p=>p.chapter===undefined));});
