import {test} from 'node:test';import assert from 'node:assert/strict';
import {fresh,buy,sell,claim,grantXP,maxHp,attack} from '../src/data/rules';import {enemies,turn} from '../src/combat/engine';import {walkable,npcs,resources} from '../src/world/map';
test('achat refuse le découvert et vente ne crée pas des objets',()=>{const s=fresh();assert.equal(buy(s,'sword'),false);assert.equal(s.gold,30);assert.equal(sell(s,'fang'),false);assert.equal(buy(s,'potion'),true);assert.equal(s.gold,18);assert.equal(s.inventory.potion,4);});
test('quête récompensée une seule fois et consomme les minerais',()=>{const s=fresh();s.quests.ore={active:true,progress:3,claimed:false};assert.equal(claim(s,'ore'),false);s.inventory.ore=3;assert.equal(claim(s,'ore'),true);assert.equal(s.inventory.ore,0);assert.equal(s.gold,55);assert.equal(claim(s,'ore'),false);});
test('victoire, riposte, butin et progression liés',()=>{const s=fresh(),e=enemies()[0];s.quests.wolves.active=true;turn(s,e,'attack',()=>0);assert.equal(s.hp,52);while(e.alive)turn(s,e,'attack',()=>0);assert.equal(s.gold,40);assert.equal(s.inventory.fang,1);assert.equal(s.quests.wolves.progress,1);assert.equal(s.xp,25);turn(s,e,'attack',()=>0);assert.equal(s.gold,40);});
test('mort ramène au village, équipement et niveaux modifient les statistiques',()=>{const s=fresh(),e=enemies()[0];s.hp=1;turn(s,e,'guard',()=>0);s.hp=1;turn(s,e,'attack',()=>0);assert.equal(s.x,530);assert.equal(s.hp,maxHp(s));s.equipped=true;assert.equal(attack(s),16);assert.equal(grantXP(s,275),2);assert.equal(s.level,3);assert.equal(s.hp,76);});
test('collisions bloquent les bâtiments, tous les objectifs sont approchables',()=>{assert.equal(walkable(100,200),false);assert.equal(walkable(530,600),true);for(const p of [...npcs,...resources,...enemies()]){let ok=false;for(let dx=-50;dx<=50;dx+=10)for(let dy=-50;dy<=50;dy+=10)if(walkable(p.x+dx,p.y+dy))ok=true;assert.ok(ok,JSON.stringify(p));}});
test('village et forêt reliés : chaque objectif accessible depuis le point de départ',()=>{const queue:[[number,number]]=[[530,600]],seen=new Set(['530,600']);for(let i=0;i<queue.length;i++){const [x,y]=queue[i];for(const [dx,dy] of [[10,0],[-10,0],[0,10],[0,-10]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(!seen.has(key)&&walkable(nx,ny)){seen.add(key);queue.push([nx,ny]);}}}for(const p of [...npcs,...resources,...enemies()])assert.ok(queue.some(([x,y])=>Math.hypot(x-p.x,y-p.y)<60),`Non accessible : ${JSON.stringify(p)}`);});
test('boucle complète : trois combats, quête, achat, équipement',()=>{const s=fresh();s.quests.wolves.active=true;for(let i=0;i<3;i++){const e=enemies()[0];s.hp=maxHp(s);while(e.alive)turn(s,e,'attack',()=>0);}assert.equal(s.quests.wolves.progress,3);assert.equal(claim(s,'wolves'),true);assert.equal(s.level,2);assert.equal(buy(s,'sword'),true);s.equipped=true;assert.equal(attack(s),18);assert.equal(s.gold,50);});
